// Code generated by ent, DO NOT EDIT.

package ent

import (
	"DeployDude/ent/predicate"
	"DeployDude/ent/project"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProjectUpdate is the builder for updating Project entities.
type ProjectUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectMutation
}

// Where appends a list predicates to the ProjectUpdate builder.
func (pu *ProjectUpdate) Where(ps ...predicate.Project) *ProjectUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetHashID sets the "hash_id" field.
func (pu *ProjectUpdate) SetHashID(s string) *ProjectUpdate {
	pu.mutation.SetHashID(s)
	return pu
}

// SetTitle sets the "title" field.
func (pu *ProjectUpdate) SetTitle(s string) *ProjectUpdate {
	pu.mutation.SetTitle(s)
	return pu
}

// SetGitURL sets the "git_url" field.
func (pu *ProjectUpdate) SetGitURL(s string) *ProjectUpdate {
	pu.mutation.SetGitURL(s)
	return pu
}

// SetDirPath sets the "dir_path" field.
func (pu *ProjectUpdate) SetDirPath(s string) *ProjectUpdate {
	pu.mutation.SetDirPath(s)
	return pu
}

// Mutation returns the ProjectMutation object of the builder.
func (pu *ProjectUpdate) Mutation() *ProjectMutation {
	return pu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *ProjectUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pu.hooks) == 0 {
		if err = pu.check(); err != nil {
			return 0, err
		}
		affected, err = pu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProjectMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = pu.check(); err != nil {
				return 0, err
			}
			pu.mutation = mutation
			affected, err = pu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pu.hooks) - 1; i >= 0; i-- {
			if pu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (pu *ProjectUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *ProjectUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *ProjectUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pu *ProjectUpdate) check() error {
	if v, ok := pu.mutation.HashID(); ok {
		if err := project.HashIDValidator(v); err != nil {
			return &ValidationError{Name: "hash_id", err: fmt.Errorf(`ent: validator failed for field "Project.hash_id": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Title(); ok {
		if err := project.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Project.title": %w`, err)}
		}
	}
	if v, ok := pu.mutation.GitURL(); ok {
		if err := project.GitURLValidator(v); err != nil {
			return &ValidationError{Name: "git_url", err: fmt.Errorf(`ent: validator failed for field "Project.git_url": %w`, err)}
		}
	}
	if v, ok := pu.mutation.DirPath(); ok {
		if err := project.DirPathValidator(v); err != nil {
			return &ValidationError{Name: "dir_path", err: fmt.Errorf(`ent: validator failed for field "Project.dir_path": %w`, err)}
		}
	}
	return nil
}

func (pu *ProjectUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   project.Table,
			Columns: project.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: project.FieldID,
			},
		},
	}
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.HashID(); ok {
		_spec.SetField(project.FieldHashID, field.TypeString, value)
	}
	if value, ok := pu.mutation.Title(); ok {
		_spec.SetField(project.FieldTitle, field.TypeString, value)
	}
	if value, ok := pu.mutation.GitURL(); ok {
		_spec.SetField(project.FieldGitURL, field.TypeString, value)
	}
	if value, ok := pu.mutation.DirPath(); ok {
		_spec.SetField(project.FieldDirPath, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// ProjectUpdateOne is the builder for updating a single Project entity.
type ProjectUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectMutation
}

// SetHashID sets the "hash_id" field.
func (puo *ProjectUpdateOne) SetHashID(s string) *ProjectUpdateOne {
	puo.mutation.SetHashID(s)
	return puo
}

// SetTitle sets the "title" field.
func (puo *ProjectUpdateOne) SetTitle(s string) *ProjectUpdateOne {
	puo.mutation.SetTitle(s)
	return puo
}

// SetGitURL sets the "git_url" field.
func (puo *ProjectUpdateOne) SetGitURL(s string) *ProjectUpdateOne {
	puo.mutation.SetGitURL(s)
	return puo
}

// SetDirPath sets the "dir_path" field.
func (puo *ProjectUpdateOne) SetDirPath(s string) *ProjectUpdateOne {
	puo.mutation.SetDirPath(s)
	return puo
}

// Mutation returns the ProjectMutation object of the builder.
func (puo *ProjectUpdateOne) Mutation() *ProjectMutation {
	return puo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *ProjectUpdateOne) Select(field string, fields ...string) *ProjectUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Project entity.
func (puo *ProjectUpdateOne) Save(ctx context.Context) (*Project, error) {
	var (
		err  error
		node *Project
	)
	if len(puo.hooks) == 0 {
		if err = puo.check(); err != nil {
			return nil, err
		}
		node, err = puo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProjectMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = puo.check(); err != nil {
				return nil, err
			}
			puo.mutation = mutation
			node, err = puo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(puo.hooks) - 1; i >= 0; i-- {
			if puo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = puo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, puo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Project)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from ProjectMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (puo *ProjectUpdateOne) SaveX(ctx context.Context) *Project {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *ProjectUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *ProjectUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (puo *ProjectUpdateOne) check() error {
	if v, ok := puo.mutation.HashID(); ok {
		if err := project.HashIDValidator(v); err != nil {
			return &ValidationError{Name: "hash_id", err: fmt.Errorf(`ent: validator failed for field "Project.hash_id": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Title(); ok {
		if err := project.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Project.title": %w`, err)}
		}
	}
	if v, ok := puo.mutation.GitURL(); ok {
		if err := project.GitURLValidator(v); err != nil {
			return &ValidationError{Name: "git_url", err: fmt.Errorf(`ent: validator failed for field "Project.git_url": %w`, err)}
		}
	}
	if v, ok := puo.mutation.DirPath(); ok {
		if err := project.DirPathValidator(v); err != nil {
			return &ValidationError{Name: "dir_path", err: fmt.Errorf(`ent: validator failed for field "Project.dir_path": %w`, err)}
		}
	}
	return nil
}

func (puo *ProjectUpdateOne) sqlSave(ctx context.Context) (_node *Project, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   project.Table,
			Columns: project.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: project.FieldID,
			},
		},
	}
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Project.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, project.FieldID)
		for _, f := range fields {
			if !project.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != project.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.HashID(); ok {
		_spec.SetField(project.FieldHashID, field.TypeString, value)
	}
	if value, ok := puo.mutation.Title(); ok {
		_spec.SetField(project.FieldTitle, field.TypeString, value)
	}
	if value, ok := puo.mutation.GitURL(); ok {
		_spec.SetField(project.FieldGitURL, field.TypeString, value)
	}
	if value, ok := puo.mutation.DirPath(); ok {
		_spec.SetField(project.FieldDirPath, field.TypeString, value)
	}
	_node = &Project{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
